import { Outfit } from "next/font/google"; // Updated import
import "./globals.css";

const outfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Added font weights
});

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfitFont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
